In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv("titanic.csv")

In [ ]:
def clean(data):
    data = data.drop(["ticket", "name", "cabin"], axis=1)
    
    cols = ["sibsp", "parch", "fare", "age"]
    for col in cols:
        data[col].fillna(data[col].median(), inplace=True)
        
    data.embarked.fillna("U", inplace=True)
    return data

In [ ]:
data = clean(df)

In [ ]:
data.head(3)

,pclass,survived,sex,age,sibsp,parch,fare,embarked,boat,body,home.dest
0,1.0,1.0,female,29.0000,0.0,0.0,211.3375,S,2,NaN,"St Louis, MO"
1,1.0,1.0,male,0.9167,1.0,2.0,151.5500,S,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1.0,0.0,female,2.0000,1.0,2.0,151.5500,S,NaN,NaN,"Montreal, PQ / Chesterville, ON"

In [ ]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
columns = ["sex", "embarked"]

for col in columns:
    data[col] = le.fit_transform(data[col])
    print(le.classes_)
      
data.head(5)

['female' 'male' nan]
['C' 'Q' 'S' 'U']

,pclass,survived,sex,age,sibsp,parch,fare,embarked,boat,body,home.dest
0,1.0,1.0,0,29.0000,0.0,0.0,211.3375,2,2,NaN,"St Louis, MO"
1,1.0,1.0,1,0.9167,1.0,2.0,151.5500,2,11,NaN,"Montreal, PQ / Chesterville, ON"
2,1.0,0.0,0,2.0000,1.0,2.0,151.5500,2,NaN,NaN,"Montreal, PQ / Chesterville, ON"
3,1.0,0.0,1,30.0000,1.0,2.0,151.5500,2,NaN,135.0,"Montreal, PQ / Chesterville, ON"
4,1.0,0.0,0,25.0000,1.0,2.0,151.5500,2,NaN,NaN,"Montreal, PQ / Chesterville, ON"

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

y = data["survived"]
X = data.drop("survived", axis=1)

X_train, X_val, y_train, y_val = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
clf = LogisticRegression(random_state=0, max_iter=1000)
clf.fit(X_train, y_train.values.ravel())

ValueError: ignored

In [ ]:
predictions = clf.predict(X_val)
from sklearn.metrics import accuracy_score
accuracy_score(y_val, predictions)

0.8888888888888888

In [ ]:
submission_preds = clf.predict(test)

In [ ]:
df = pd.DataFrame({"PassengerId": test_ids.values,
                   "Survived": submission_preds,
                  })

In [ ]:
df.to_csv("submission.csv", index=False)